const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  G00GLE_SIGN_IN_START: 'G00GLE_SIGN_IN_START',
  G00GLE_SIGN_IN_SUCCESS: 'G00GLE_SIGN_IN_SUCCESS',
  G00GLE_SIGN_IN_FAILURE: 'G00GLE_SIGN_IN_FAILURE',
  EMAIL_SIGN_IN_START: ' EMAIL_SIGN_IN_START',
  EMAIL_SIGN_IN_SUCCESS: ' EMAIL_SIGN_IN_SUCCESS',
  EMAIL_SIGN_IN_FAILURE: ' EMAIL_SIGN_IN_FAILURE',
};

export default UserActionTypes;
